const heading = "<p>Gửi cô gái của tớ, </p><br/>";

const wishesData = [
  "^700Cuối cùng thì ngày này cũng tới nhỉ hehe. Chắc cậu cũng đợi đến khoảnh khắc này  lâu lắm rùi. Mong rằng ngày hôm nay cậu có thể buông thả những cái mệt mỏi thi cử chết tiệt kia đi để tận hưởng ngày đặc biệt nhất trong năm với cậu^500, và với cả tớ nữa.",
  "Hy vọng cậu đã có một năm thực sự hạnh phúc, với những người luôn yêu thương cậu. Nếu năm nay chưa được như cậu mong muốn, thì cũng đừng vì những điều không may đó làm cậu có suy nghĩ không tích cực về bản thân nhé 😉, mình còn cả chặng đường dài ở phía trước mà và quan trọng hơn là cậu thực sự tuyệt vời đóa 🥰.",
  "Chúc cho chặng đường tuổi đôi mươi của cậu thực sự viên mãn theo cách mà cậu muốn. Chúc cô gái mọi điều tốt đẹp nhất trong những năm tháng tuổi trẻ sắp tới của mình. Chúc cho sự may mắn luôn ở bên cạnh cậu, đồng hành cùng cậu trong mọi dự định trong tương lai. Chúc cậu dù ở đâu, bất cứ khi nào, cũng nhận được sự giúp đỡ, che chở, chia sẻ và cảm thông từ những người thực sự yêu thương cậu. Chúc cô gái mau quên đi những chuyện không như ý, những người đã làm cậu phải bận lòng. Chúc cậu mỗi ngày đều cười thật tươi, dẫu cho hôm ấy cậu có gặp gỡ ai, gặp những chuyện buồn đi chăng nữa. Mọi chuyện đều có thể vượt qua được, nếu cậu tin vào chính bản thân mình 😊.",
  "Cảm ơn cậu đã ở bên cạnh nguyenducloc này trong năm vừa rùi. Cậu thực sự làm tớ tốt hơn í hic 😭...^1000 Tớ luôn mong rằng có thể ở bên cạnh giúp đỡ cậu nhiều nhất có thể. Nếu cóa những lúc nào tớ làm cậu buồn thì tớ xin lũi nhìu nhìu nhé 😉. Anyway, tớ chỉ mong những điều tốt nhất đến với cậu thui 🥰. ",
  "<p>My girl, I wish you nothing but the best. I’m proud of you.^500 I^1000 luv^1000 you^1000 sooooooo much ❣️.</p><br/><p>Your crazy man,</p><p>David Lok.</p>",
];

export default wishesData.map((e) => heading + e);
